### ISSUE TITLE
Q:  Is there a client app using this?

### ISSUE THREAD

**Issue by fat-tire** [jonahwh/tesla-api-client#1]
I see this library was updated as recently as 4 days ago-- it looks sweet-- is there an OS Android Tesla app in progress somewhere that uses tesla-api-client??

There have been a [few](https://uxdesign.cc/redesigning-the-mobile-app-that-tesla-deserves-d89b2c9ef9a0) attempts to redesign the app, just wondering if anyone started actually doing it.

I should add there are a lot of use cases for a simple alternative app, one being the ability to use it on Chromebooks.

**Comment by kurthuwig** [comment]
Yes, I will use it for my upcoming project.

**Comment by fat-tire** [comment]
Ah, will this be an open source client so I can contribute?

**Comment by jonahwh** [comment]
Oof, sorry I totally missed all the issues on this repo until just now!

I use this as the backing for my app, [Tasker Plugin for Tesla](https://play.google.com/store/apps/details?id=com.crazydog.teslatasker&hl=en_US)
