### ISSUE TITLE
docs/AuthenticationApi.md is outdated

### ISSUE THREAD

**Issue by Alex0176** [jonahwh/tesla-api-client#2]
Hallo, the documentation is a little bit outdated, because the docs/AuthenticationApi.md did not work with the last version anymore. 

CreateAccessTokenResponse result = apiInstance.createOauthToken(body);
can not be casted.

**Comment by jonahwh** [comment]
Hi Alex, sorry for the late response, I did not have notifications on for issues in this repo - 

Are you still having this issue? The docs are auto-generated by `swagger-codegen`, so I'd assume they are accurate, and the example looks similar to what I am using in production code.

**Comment by jonahwh** [comment]
I just added an example to the README that may help you. Feel free to reply if you're still having issues.
